name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install openssh-client -y

      - name: Create SSH directory if not exists
        run: |
          if [ ! -d ~/.ssh ]; then
            mkdir -p ~/.ssh
          fi

      - name: Use SSH key for authentication
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Run deployment script
        run: ssh -i ~/.ssh/id_rsa saransh@20.244.27.5 'bash /home/saransh/event-portal/script.sh'
